#----------------------------------------------------------------------
# This file was generated by C:\Miniconda3\envs\origami-ms\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icons = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAGEAAAAxCAIAAABF6lADAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEISURBVGhD7dYxTgJBFIDhuQ0egbNQ'
    b'qDRW9B7KRokkRivRhA4TOgsqDIWh4AbrBEYZNmt+qN//5yWbNzPVV23anllKqQlW2+hxsRwf'
    b'T7n4LbrR1XSd7ret6T1tyvWu0EbXXUD7qZlCG908fw4f5mWpurybDccfZQluNHr/ylOWqtHb'
    b'qj7XqMvo+FwjjTrSiNOI04g7GA1e13kmi2Vr9uflUXCj29mq9ev4N/2X7/IouFGuk6kGykU3'
    b'OiWNuIhGF+eUgSIala/9n0acRpxGnEacRpxGnEacRpxGnEacRpxGnEacRpxGnEacRpxGnEac'
    b'RpxGnEacRpxGnEacRpxGnEacRpxGnEZU0/wAfFKwEdpIHtUAAAAASUVORK5CYII=')

